defaults:
  - model: mantis_v2
  - train_wrapper: mantis_probe_trainer
  - writer: wandb
  - _self_
optimizer: null

trainer:
  num_epochs: 1000
  fine_tuning_type: "head"
  path: "paris-noah/MantisV2"
  checkpoint_name: "mantis_probe"
  checkpoints: "checkpoints"
  results: "results"
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: True # if True, will override the previous run with the same name
  save_period: 5 # checkpoint each save_period epochs in addition to the best epoch
  save_dir: "saved"
  seed: 1
